/*****************************************************************************
 *
 * This MobilityDB code is provided under The PostgreSQL License.
 * Copyright (c) 2016-2023, Université libre de Bruxelles and MobilityDB
 * contributors
 *
 * MobilityDB includes portions of PostGIS version 3 source code released
 * under the GNU General Public License (GPLv2 or later).
 * Copyright (c) 2001-2023, PostGIS contributors
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without a written
 * agreement is hereby granted, provided that the above copyright notice and
 * this paragraph and the following two paragraphs appear in all copies.
 *
 * IN NO EVENT SHALL UNIVERSITE LIBRE DE BRUXELLES BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
 * LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 * EVEN IF UNIVERSITE LIBRE DE BRUXELLES HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * UNIVERSITE LIBRE DE BRUXELLES SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
 * AN "AS IS" BASIS, AND UNIVERSITE LIBRE DE BRUXELLES HAS NO OBLIGATIONS TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *****************************************************************************/

/**
 * @brief A simple program that reads from a CSV file synthetic trip data in
 * Brussels generated by the MobilityDB-BerlinMOD generator,
 * https://github.com/MobilityDB/MobilityDB-BerlinMOD
 * assembles the trips from the individual observations, and write them in a
 * CSV file named "trips_new.csv" which corresponds to the file "trips.csv" in
 * the current directory.
 *
 * The input file is
 * - `trips_instants.csv`: individual observations from 55 trips of 5 cars
 *   during 4 days obtained from the generator at scale factor 0.005.
 *   This file is generated by the program `05_meos_disassemble_berlinmod`.
 * In the above file, the coordinates are given in the 3857 coordinate system,
 * https://epsg.io/3857
 * and the timestamps are given in the Europe/Brussels time zone.
 * The input file can be generated by running the program
 * `05_meos_disassemble_berlinmod.c` in the current directory
 * This simple program does not cope with erroneous inputs, such as missing
 * fields or invalid values.
 *
 * The program can be build as follows
 * @code
 * gcc -Wall -g -I/usr/local/include -o 03_meos_assemble_berlinmod 03_meos_assemble_berlinmod.c -L/usr/local/lib -lmeos
 * @endcode
 */

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <meos.h>
#include <unistd.h>
#include "../initialize_kafka.h"

/* Maximum number of instants in an input trip */
#define MAX_INSTANTS 50000
/* Number of instants in a batch for printing a marker */
#define NO_INSTANTS_BATCH 1000
/* Maximum length in characters of a header record in the input CSV file */
#define MAX_LENGTH_HEADER 1024
/* Maximum length in characters of a point in the input data */
#define MAX_LENGTH_POINT 100
/* Maximum length in characters of a date in the input data */
#define MAX_LENGTH_DATE 12
/* Maximum length in characters of a timestamp in the input data */
#define MAX_LENGTH_TIMESTAMP 32
/* Maximum number of trips */
#define MAX_TRIPS 5

typedef struct
{
    int tripid;
    int vehid;
    DateADT day;
    int seq;
    GSERIALIZED *point;
    TimestampTz t;
} trip_input_record;

typedef struct
{
    int tripid;      /* Identifier of the trip */
    int vehid;       /* Identifier of the vehicle */
    DateADT day;     /* Day of the trip */
    int seq;         /* Number of the trip in the day of the trip */
    int numinstants; /* Number of input instants */
    TInstant *trip_instants[MAX_INSTANTS]; /* Array of instants for the trip */
    Temporal *trip;  /* Trip constructed from the input instants */
} trip_output_record;


/* Main program */
int main(int argc, char **argv)
{

  /* Initialize MEOS */
  meos_initialize(NULL, NULL);

  rd_kafka_t *rk;
  char * tripfile = argv[1];
  char * topic = argv[2];

  /* Get start time */
  clock_t t;
  t = clock();

  rk = initialize_producer("localhost:9092");
  if (rk == NULL)
  {
    printf(" KAFKA CLIENT HAS NOT CONFIGURED PROPERLY \n ");
    return 1;
  }
  /* Allocate space to build the trips */
  trip_output_record trips[MAX_TRIPS] = {0};
  /* Number of trips */
  int numtrips = 0;
  /* Iterator variables */
  int i, j;
  /* Return value */
  int return_value = 0;

  /* Substitute the full file path in the first argument of fopen */
  FILE *file = fopen(tripfile, "r");

  if (! file)
  {
    printf("Error opening file %s\n", tripfile);
    meos_finalize();
    return 1;
  }

  trip_input_record rec;
  int no_records = 0;
  int no_nulls = 0;
  char header_buffer[MAX_LENGTH_HEADER];
  char point_buffer[MAX_LENGTH_POINT];
  char date_buffer[MAX_LENGTH_DATE];
  char timestamp_buffer[MAX_LENGTH_TIMESTAMP];

  /* Read the first line of the file with the headers */
  fscanf(file, "%1023s\n", header_buffer);

  printf("Reading the instants (one marker every %d instants)\n",
         NO_INSTANTS_BATCH);

  /* Continue reading the file */
  do
  {
    int read = fscanf(file, "%d,%d,%10[^,],%d,%99[^,],%31[^\n]\n",
                      &rec.tripid, &rec.vehid, date_buffer, &rec.seq, point_buffer,
                      timestamp_buffer);
    /* Transform the string representing the date into a date value */
    rec.day = pg_date_in(date_buffer);
    /* Transform the string representing the trip into a temporal value */
    rec.point = pgis_geometry_in(point_buffer, -1);
    /* Transform the string representing the timestamp into a timestamp value */
    rec.t = pg_timestamp_in(timestamp_buffer, -1);
    /* Transform the string representing the trip into a temporal value */
    TInstant *inst = tpointinst_make(rec.point, rec.t);

    if (read == 6)
    {
      no_records++;
      if (no_records % NO_INSTANTS_BATCH == 0)
      {
        printf("*");
        fflush(stdout);
      }
    }

    if (read != 6 && ! feof(file))
    {
      printf("Record with missing values ignored\n");
      no_nulls++;
    }

    if (ferror(file))
    {
      printf("Error reading the input file");
      return_value = 1;
      goto cleanup;
    }

    /* Find the place to store the new instant */
    int trip = -1;
    for (i = 0; i < MAX_TRIPS; i++)
    {
      if (trips[i].tripid == rec.tripid)
      {
        trip = i;
        break;
      }
    }
    if (trip < 0)
    {
      trip = numtrips++;
      if (trip == MAX_TRIPS)
      {
        printf("The maximum number of trips in the input file is bigger than %d",
               MAX_TRIPS);
        return_value = 1;
        goto cleanup;
      }
    }

    /*
     * Store the input values
     */
    trips[trip].tripid = rec.tripid;
    trips[trip].vehid = rec.vehid;
    trips[trip].day = rec.day;
    trips[trip].seq = rec.seq;
    trips[trip].trip_instants[trips[trip].numinstants++] = inst;
  } while (!feof(file));

  /* Close the input file */
  fclose(file);

  printf("\n%d records read from file 'trip_instants.csv'.\n%d incomplete records ignored.\n",
         no_records, no_nulls);
  printf("%d trips read.\n", numtrips);

  /* Construct the trips */
  for (i = 0; i < numtrips; i++)
  {
    trips[i].trip = (Temporal *) tsequence_make(
            (const TInstant **) trips[i].trip_instants,
            trips[i].numinstants, true, true, LINEAR, true);
    printf("TripId: %d, Number of input instants: %d, Distance travelled %lf\n",
           trips[i].tripid, trips[i].numinstants, tpoint_length(trips[i].trip));
  }

  /* Write to kafka buffer */


  if (rk == NULL)
  {
    printf(" KAFKA CLIENT HAS NOT CONFIGURED PROPERLY \n ");

    return 1;
  }

  /* Loop for each trip */

  printf("Writing the assembled trips to Kafka buffer ... \n");
  for (i = 0; i < numtrips; i++)
  {

    rd_kafka_resp_err_t err;

    char *date_str = pg_date_out(trips[i].day);
    size_t length;
    /* Encode using server machine endian */
    char *trip_str = temporal_as_hexwkb(trips[i].trip, WKB_EXTENDED, &length);
    int len = snprintf(NULL, 0, "%d,%d,%s,%d,%s\n", trips[i].tripid, trips[i].vehid,date_str, trips[i].seq, trip_str);
    char * line = (char*) malloc(len*sizeof(char));


    sprintf(line, "%d,%d,%s,%d,%s\n", trips[i].tripid, trips[i].vehid,date_str, trips[i].seq, trip_str);


    retry:
    err = rd_kafka_producev(
            /* Producer handle */
            rk,
            /* Topic name */
            RD_KAFKA_V_TOPIC(topic),
            /* Make a copy of the payload. */
            RD_KAFKA_V_MSGFLAGS(RD_KAFKA_MSG_F_COPY),
            /* Message value and length */
            RD_KAFKA_V_VALUE(line, (size_t)len),
            /* Per-Message opaque, provided in
             * delivery report callback as
             * msg_opaque. */
            RD_KAFKA_V_OPAQUE(NULL),
            /* End sentinel */
            RD_KAFKA_V_END);

    if (err)
    {
      /*
       * Failed to *enqueue* message for producing.
       */
      fprintf(stderr,
              "%% Failed to produce to topic %s: %s\n", topic,
              rd_kafka_err2str(err));

      if (err == RD_KAFKA_RESP_ERR__QUEUE_FULL)
      {
        /* If the internal queue is full, wait for
         * messages to be delivered and then retry.
         * The internal queue represents both
         * messages to be sent and messages that have
         * been sent or failed, awaiting their
         * delivery report callback to be called.
         *
         * The internal queue is limited by the
         * configuration property
         * queue.buffering.max.messages and
         * queue.buffering.max.kbytes */
        rd_kafka_poll(rk,
                      1000 /*block for max 1000ms*/);
        goto retry;
      }
    }
    rd_kafka_poll(rk,100);

  }



  printf("Writing done.\n");

  /* Calculate the elapsed time */
  t = clock() - t;
  double time_taken = ((double) t) / CLOCKS_PER_SEC;
  printf("The program took %f seconds to execute\n", time_taken);

/* Clean up */
  sleep(2);
  cleanup:

  rd_kafka_producev(
          /* Producer handle */
          rk,
          /* Topic name */
          RD_KAFKA_V_TOPIC(topic),
          /* Make a copy of the payload. */
          RD_KAFKA_V_MSGFLAGS(RD_KAFKA_MSG_F_COPY),
          /* Message value and length */
          RD_KAFKA_V_VALUE("end", 3),
          /* Per-Message opaque, provided in
           * delivery report callback as
           * msg_opaque. */
          RD_KAFKA_V_OPAQUE(NULL),
          /* End sentinel */
          RD_KAFKA_V_END);
  rd_kafka_poll(rk, 0 /*non-blocking*/);


  /* Free memory */
  for (i = 0; i < numtrips; i++)
  {
    free(trips[i].trip);
    for (j = 0; j < trips[i].numinstants; j++)
      free(trips[i].trip_instants[j]);
  }


  rd_kafka_flush(rk, 10 * 1000 /* wait for max 10 seconds */);
  /* Finalize MEOS */
  meos_finalize();
  rd_kafka_destroy(rk);

  return return_value;
}
